// In contrast to sim_cell_division1.cl, this kernel consolidates the data generated by sim_cell_division1.cl.

#define GROUP_SIZE 256

kernel void concatenate(global uint* out_new_cells,
						global const uint* in_new_cells,
						global const uint* in_new_cell_group_size)
{
	uint local_count = in_new_cell_group_size[get_group_id(0)];
	uint local_offset = 0;

	// Get the offset by adding up all the sizes produced in the array:
	for(uint i=0; i<get_group_id(0); i++)
	{
		local_offset += in_new_cell_group_size[i];
	}

	// Perform concatenation:
	if(get_local_id(0) < local_count)
	{
		out_new_cells[local_offset + get_local_id(0)] = in_new_cells[get_global_id(0)];
	}
};
